name: Lint
run-name: Lint

on:
  pull_request:
    branches: ["**"]

permissions: {}

env:
  environment: base

jobs:
  lint:
    permissions:
      contents: read

    name: Lint
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pre-commit
        run: pip install pre-commit==4.0.1

      - name: Validate hook manifests
        run: |
          pre-commit validate-manifest
          pre-commit validate-config

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          scandir: scripts
